### ISSUE TITLE
wtwt

### ISSUE THREAD

**Issue by DavidChengweiLiu** [cambridge-wtwt/acl2020-wtwt-tweets#1]
I want to know if I need to get the tweet text by myself through tweet id?

**Comment by XM-WANG** [comment]
Hi,

I have the same problem. If you have any solutions?

**Comment by jakobberndt** [comment]
Hello,

Yes, in principle you should be able to retrieve most of the tweets through the tweet ids using the Twitter API. Note, however, that some tweets might not be available anymore - e.g. because the users deleted the tweet or their entire account. This is a known problem with Twitter datasets (see e.g. [this paper](https://arxiv.org/pdf/1709.09186.pdf) by Arkaitz Zubiaga which discusses this more in detail).

In case you encounter this problem, please contact us at cc918@cam.ac.uk. Upon signing our data agreement, we should be able to provide you with the full dataset.

**Comment by XM-WANG** [comment]
> Yes, in principle you should be able to retrieve most of the tweets through the tweet ids using the Twitter API. Note, however, that some tweets might not be available anymore - e.g. because the users deleted the tweet or their entire account. This is a known problem with Twitter datasets (see e.g. [this paper](https://arxiv.org/pdf/1709.09186.pdf) by Arkaitz Zubiaga which discusses this more in detail).

Got it! Thanks for your help!
